name: HardcorePlus
version: 1.0
main: me.ziomki.hardcoreplus.HardcorePlus
api-version: 1.19

commands:
  chance:
    description: test
    usage: /<command>
  utrudnienia:
    description: Lista utrudnień trybu hardcore
    usage: /<command>